### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by junorouse** [junorouse/valid-xss-checker#3]
- [ ] css framework 쓰던가 해서 xss view table 이쁘게
- [ ] 테이블 누르면 상세정보
- [ ] 추가할때 query string -> json
- [ ] python 으로 recursive crawler 만들기

- [ ] 닉네임, 문제명 등등 등록할 수 있게
- [ ] 실시간 반영

- [ ] 검색 기능 추가
